"""Authoritative names shared by bkg's runtime adapters."""

from enum import StrEnum


class EnvironmentVariable(StrEnum):
    """Environment names interpreted by bkg rather than passed through."""

    GITHUB_TOKEN = "GITHUB_TOKEN"  # noqa: S105
    GH_TOKEN = "GH_TOKEN"  # noqa: S105
    GITHUB_OWNER = "GITHUB_OWNER"
    GITHUB_REPO = "GITHUB_REPO"
    GITHUB_BRANCH = "GITHUB_BRANCH"
    GITHUB_ACTOR = "GITHUB_ACTOR"
    GITHUB_RUN_ID = "GITHUB_RUN_ID"
    BKG_HANDOFF_CONTROL_REF = "BKG_HANDOFF_CONTROL_REF"
    BKG_HANDOFF_POLL_SECONDS = "BKG_HANDOFF_POLL_SECONDS"
    BKG_HANDOFF_GIT_TIMEOUT_SECONDS = "BKG_HANDOFF_GIT_TIMEOUT_SECONDS"
    BKG_ROOT = "BKG_ROOT"
    BKG_ENV = "BKG_ENV"
    BKG_OWNERS = "BKG_OWNERS"
    BKG_OPTOUT = "BKG_OPTOUT"
    BKG_OWNER_ID_CACHE = "BKG_OWNER_ID_CACHE"
    BKG_INDEX_TBL_OWN = "BKG_INDEX_TBL_OWN"
    BKG_INDEX_TBL_PKG = "BKG_INDEX_TBL_PKG"
    BKG_INDEX_TBL_VER = "BKG_INDEX_TBL_VER"
    BKG_MODE = "BKG_MODE"
    BKG_MAX_LEN = "BKG_MAX_LEN"
    BKG_IS_FIRST = "BKG_IS_FIRST"
    BKG_INDEX = "BKG_INDEX"
    BKG_INDEX_DB = "BKG_INDEX_DB"
    BKG_INDEX_SQL = "BKG_INDEX_SQL"
    BKG_INDEX_DIR = "BKG_INDEX_DIR"
    BKG_MAX_VERSION_PAGES = "BKG_MAX_VERSION_PAGES"
    BKG_TAG_CACHE_PAGES = "BKG_TAG_CACHE_PAGES"
    BKG_APPEND_TAGGED_VERSIONS_LIMIT = "BKG_APPEND_TAGGED_VERSIONS_LIMIT"
    BKG_OWNER_DISCOVERY_MAX_PAGES = "BKG_OWNER_DISCOVERY_MAX_PAGES"
    BKG_SNAPSHOT_ROTATION_THRESHOLD_BYTES = "BKG_SNAPSHOT_ROTATION_THRESHOLD_BYTES"
    BKG_PARALLEL_ASYNC_MAX_JOBS = "BKG_PARALLEL_ASYNC_MAX_JOBS"
    BKG_OWNER_UPDATE_STOP_GRACE = "BKG_OWNER_UPDATE_STOP_GRACE"
    BKG_DOCKER_SIZE_FALLBACK = "BKG_DOCKER_SIZE_FALLBACK"
    BKG_DOCKER_PLATFORM = "BKG_DOCKER_PLATFORM"
    BKG_DOCKER_PULL_TIMEOUT = "BKG_DOCKER_PULL_TIMEOUT"
    BKG_DOCKER_COMMAND_TIMEOUT = "BKG_DOCKER_COMMAND_TIMEOUT"
    BKG_GITHUB_API_URL = "BKG_GITHUB_API_URL"
    BKG_HTTP_CONNECT_TIMEOUT = "BKG_HTTP_CONNECT_TIMEOUT"
    BKG_HTTP_READ_TIMEOUT = "BKG_HTTP_READ_TIMEOUT"
    BKG_HTTP_WRITE_TIMEOUT = "BKG_HTTP_WRITE_TIMEOUT"
    BKG_HTTP_POOL_TIMEOUT = "BKG_HTTP_POOL_TIMEOUT"
    BKG_HTTP_TOTAL_TIMEOUT = "BKG_HTTP_TOTAL_TIMEOUT"
    BKG_HTTP_MAX_ATTEMPTS = "BKG_HTTP_MAX_ATTEMPTS"
    BKG_HTTP_INITIAL_BACKOFF = "BKG_HTTP_INITIAL_BACKOFF"
    BKG_HTTP_MAX_BACKOFF = "BKG_HTTP_MAX_BACKOFF"
    BKG_GITHUB_REST_RESERVE = "BKG_GITHUB_REST_RESERVE"
    BKG_HTTP_USER_AGENT = "BKG_HTTP_USER_AGENT"
    BKG_SQLITE_BUSY_TIMEOUT_MS = "BKG_SQLITE_BUSY_TIMEOUT_MS"
    BKG_SQLITE_MAX_ATTEMPTS = "BKG_SQLITE_MAX_ATTEMPTS"
    BKG_SQLITE_RETRY_DELAY_SECS = "BKG_SQLITE_RETRY_DELAY_SECS"
    BKG_OWNER_RETRY_INITIAL_SECONDS = "BKG_OWNER_RETRY_INITIAL_SECONDS"
    BKG_OWNER_RETRY_MAX_SECONDS = "BKG_OWNER_RETRY_MAX_SECONDS"
    BKG_OWNER_ARRAY_MAX_BYTES = "BKG_OWNER_ARRAY_MAX_BYTES"
    BKG_OWNER_ARRAY_ADAPTIVE_MAX_PROBE = "BKG_OWNER_ARRAY_ADAPTIVE_MAX_PROBE"
    BKG_OWNER_ARRAY_DB_ESTIMATE_HEADROOM_PERCENT = (
        "BKG_OWNER_ARRAY_DB_ESTIMATE_HEADROOM_PERCENT"
    )
    BKG_OWNER_ARRAY_DB_FALLBACK_VERSION_LIMIT = (
        "BKG_OWNER_ARRAY_DB_FALLBACK_VERSION_LIMIT"
    )
    BKG_OWNER_ARRAY_VERSION_LIMIT = "BKG_OWNER_ARRAY_VERSION_LIMIT"
    BKG_OWNER_ARRAY_DB_VERSION_LIMIT = "BKG_OWNER_ARRAY_DB_VERSION_LIMIT"
    BKG_JSON_XML_MAX_BYTES = "BKG_JSON_XML_MAX_BYTES"
    BKG_JSON_XML_HARD_MAX_BYTES = "BKG_JSON_XML_HARD_MAX_BYTES"


class StateKey(StrEnum):
    """Exact persisted state names owned or retired by the Python runtime."""

    BATCH_FIRST_STARTED = "BKG_BATCH_FIRST_STARTED"
    BATCH_MARKER = "BKG_BATCH_MARKER"
    PACKAGE_PROGRESS_MARKER = "BKG_PACKAGE_PROGRESS_MARKER"
    CALLS_TO_API = "BKG_CALLS_TO_API"
    DIFF = "BKG_DIFF"
    DISCOVERED_CONNECTION_OWNERS = "BKG_DISCOVERED_CONNECTION_OWNERS"
    GRAPHQL_LAST_COST = "BKG_GRAPHQL_LAST_COST"
    GRAPHQL_REMAINING = "BKG_GRAPHQL_REMAINING"
    GRAPHQL_RESET_AT = "BKG_GRAPHQL_RESET_AT"
    LAST_EXPLORE_DATE = "BKG_LAST_EXPLORE_DATE"
    LAST_OWNERS_QUEUE_DATE = "BKG_LAST_OWNERS_QUEUE_DATE"
    LAST_SCANNED_ID = "BKG_LAST_SCANNED_ID"
    MIN_CALLS_TO_API = "BKG_MIN_CALLS_TO_API"
    MIN_RATE_LIMIT_START = "BKG_MIN_RATE_LIMIT_START"
    OUT = "BKG_OUT"
    RATE_LIMIT_START = "BKG_RATE_LIMIT_START"
    REST_LIMIT = "BKG_REST_LIMIT"
    REST_REMAINING = "BKG_REST_REMAINING"
    REST_RESET_AT = "BKG_REST_RESET_AT"
    REST_TO_TOP = "BKG_REST_TO_TOP"
    SCRIPT_START = "BKG_SCRIPT_START"
    TIMEOUT = "BKG_TIMEOUT"
    LEGACY_OWNERS_QUEUE = "BKG_OWNERS_QUEUE"
    OBSOLETE_PAGE_ALL = "BKG_PAGE_ALL"
    OBSOLETE_INDEX_CLEANUP_DONE = "BKG_INDEX_CLEANUP_DONE"


class StatePrefix(StrEnum):
    """Persisted compatibility families whose suffixes are runtime identities."""

    LEGACY_VERSIONS = "BKG_VERSIONS_"
    LEGACY_PACKAGES = "BKG_PACKAGES_"
    LEGACY_OWNER_SCAN = "BKG_OWNER_SCAN_"
    LEGACY_OWNER_PAGE = "BKG_PAGE_"
    LEGACY_OWNER_SCRATCH = "BKG_OWNERS_"


class RunFile(StrEnum):
    """Transient planning files owned or retired by the Python runtime."""

    PACKAGES_ALL = "packages_all"
    ALL_OWNERS_IN_DB = "all_owners_in_db"
    OWNERS_PARTIALLY_UPDATED = "owners_partially_updated"
    OWNERS_STALE = "owners_stale"
    OWNERS_SCANNED_WITHOUT_PACKAGES = "owners_scanned_without_packages"
    LEGACY_PACKAGES_ALREADY_UPDATED = "packages_already_updated"
    LEGACY_PACKAGES_TO_UPDATE = "packages_to_update"
    LEGACY_ALL_OWNERS_TO_UPDATE = "all_owners_tu"
    LEGACY_OWNERS_UPDATED = "owners_updated"
    LEGACY_OWNERS_DEFERRED = "owners_deferred"


def legacy_owner_scan_key(owner_id: str) -> str:
    """Return the former shell scan-marker key for one owner ID."""

    return f"{StatePrefix.LEGACY_OWNER_SCAN}{owner_id}"


def legacy_owner_page_key(owner_id: str) -> str:
    """Return the former shell scan-page key for one owner ID."""

    return f"{StatePrefix.LEGACY_OWNER_PAGE}{owner_id}"
